### PR TITLE
Add Combined Endpoint

### PR DESCRIPTION
**Pull request by Hsieh-1989**
This code is from your previous episode, I think it's a great feature to have in this framework!

### CODE REVIEW

**Comment by chriseidhof** [comment]
Hi @Hsieh-1989 ! I wonder if we should do this in a separate package... just to keep the core as tiny as possible. WDYT?

**Comment by Hsieh-1989** [comment]
Yes! separate it to another package is a good option.
But It seems to me that this library is providing a type-safe way to bundle up a request & response to endpoint, and the combining functionality is a way to achieve this purpose.
So make it as part of core functionality seems a good idea for me.

**Comment by Hsieh-1989** [comment]
I created another [Package](https://github.com/Hsieh-1989/CombinedEndpoint) for this, so I closed it. Thanks for the advice!

**Comment by chriseidhof** [comment]
Thank you, I've added it to the readme =)

**Pull request closed without merging**
